### ISSUE TITLE
support gulp.js 

### ISSUE THREAD

**Issue by itaymesh** [twitter-archive/css-flip#11]
Hi
I've been added gulp.js support for css-filp.
I was interesting to know if you'd like me to share the code so you can added it to the repository.
Thanks
Itay

**Comment by necolas** [comment]
No thanks. We're not going to include build-tool wrappers here. You can maintain the gulp wrapper/plugin.

**Comment by itaymesh** [comment]
Ok, I will.
Thanks!

On Sat, Apr 19, 2014 at 8:48 PM, Nicolas Gallagher <notifications@github.com

> wrote:
> 
> No thanks. We're not going to include build-tool wrappers here. You can
> maintain the gulp wrapper/plugin.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/twitter/css-flip/issues/11#issuecomment-40875791
> .

## 

איתי רז

0544.635.797
03.5664254
studioraz.co.il
