### ISSUE TITLE
background-position 0 converts to 100%

### ISSUE THREAD

**Issue by ashhitch** [twitter-archive/css-flip#20]
When running css-flip on my project the background-position value gets converted from 0 to 100%

e.g:

```
background-position: 0 -100px;
```

becomes:

```
background-position: 100% -100px;
```

Is there a good reason for this or a bug?

**Comment by necolas** [comment]
Well `0` is the same as `left` or `0%`, so we flip it to `100%` like we flip `left` to `right`. But I can see how that might not be expected when working with sprites. Perhaps we should only flip `0%` and assume `0` means `0px`.

**Comment by ashhitch** [comment]
"Perhaps we should only flip 0% and assume 0 means 0px." - I would say this is the best solution. 
For now i am just using the `/*@noflip*/` to stop it happening
