### ISSUE TITLE
Cannot find module '../lib/css-flip'

### ISSUE THREAD

**Issue by brainhax** [twitter-archive/css-flip#21]
I been trying to use it and then posted on 

http://stackoverflow.com/questions/24055064/how-to-use-css-flip-bidi-flipper-with-node-js

Is this the proper way to use it. Or its a bug .

Please have a look.
thank you

**Comment by necolas** [comment]
Yeah, it's a bug. Fixed by 89d1f21ef3107d7c610f205a5a4af6a957938f84. It will be fixed in the next release, which will happen when reworkcss/css gets a new release.
