### ISSUE TITLE
Support for :before and :after pseudo elements

### ISSUE THREAD

**Issue by ondrejsevcik** [twitter-archive/css-flip#23]
Hi, could you please add new option to swap :before and :after pseudo elements? I'm using font-icons that are applied to element via those pseudo class and in RTL I need them to be swapped.

![Example](http://i.imgur.com/YZeJrCR.png)
![Code](http://i.imgur.com/YoCbY2z.png)

**Comment by necolas** [comment]
We can't flip every `:before` to `:after` and vice versa, because the use cases for pseudo-elements are many. You're better off using an empty element for your icon, then this issue goes away.

**Comment by ondrejsevcik** [comment]
You are right, but this could be optional feature.
