### ISSUE TITLE
Remove flipping of vendor prefixed properties

### ISSUE THREAD

**Issue by necolas** [twitter-archive/css-flip#5]
We should consider doing this.

**Comment by ljharb** [comment]
If you're going to flip "foo", you'd need to also flip "-webkit-foo" etc, otherwise you're only doing the flipping in some browsers.

**Comment by necolas** [comment]
The only vendor prefixed properties we currently support are `border-radius` and `box-shadow`, neither of which are needed anymore, and both of which could be automatically prefixed in a later stage by a tool like autoprefixer. (That's how we do it for twitter.com)

**Comment by ljharb** [comment]
"needed anymore" depends on your supported browser list, and a tool like this should be agnostic about that. If we find prefixed properties, we should support flipping them rather than requiring that users both use a tool like autoprefixer, and also use them in the right order.
