### ISSUE TITLE
border-radius doesn't require prefixes

### ISSUE THREAD

**Issue by zlatanvasovic** [twitter-archive/css-flip#9]
Currently, there is a support for `-webkit-` and `-moz-` prefixes of `border-radius`, but `border-radius` doesn't require prefixes in any browser.

Why are they still here?

**Comment by ljharb** [comment]
It certainly does require prefixes in some browsers - just not in current ones.

I'm fine with making the inclusion of these aliases opt-in or opt-out, but please keep them configurable.

**Comment by zlatanvasovic** [comment]
I agree with you @ljharb, they should be configurable.

**Comment by necolas** [comment]
Effectively a dupe of #5

**Comment by zlatanvasovic** [comment]
Yes, duplicate.
